# __init__.py
VERSION = '1.0.0'
TITLE = 'ComfyUI Motion Effects Pack'
DESCRIPTION = 'After Effects-style motion effects pack containing Wiggle, Optical Compensation, EDL Parser, Video Merger, Vibe Music Engine, Base Path, Simple Image Loader, Number Padder, Text File Loader, ImgBB Uploader, ComfyUI Tuple Counter, File Path Processor, Moving Titles and Anthropic Chat nodes'
COFFEE_LINK = "https://buymeacoffee.com/eyb8tkx3to"

from .wiggle_node import NODE_CLASS_MAPPINGS as WIGGLE_NODE_CLASS_MAPPINGS
from .wiggle_node import NODE_DISPLAY_NAME_MAPPINGS as WIGGLE_NODE_DISPLAY_NAME_MAPPINGS
from .optical_compensation_node import NODE_CLASS_MAPPINGS as OPTICAL_NODE_CLASS_MAPPINGS
from .optical_compensation_node import NODE_DISPLAY_NAME_MAPPINGS as OPTICAL_NODE_DISPLAY_NAME_MAPPINGS
from .edl_parser_node import NODE_CLASS_MAPPINGS as EDL_NODE_CLASS_MAPPINGS
from .edl_parser_node import NODE_DISPLAY_NAME_MAPPINGS as EDL_NODE_DISPLAY_NAME_MAPPINGS
from .videomerger import NODE_CLASS_MAPPINGS as VIDEO_MERGER_NODE_CLASS_MAPPINGS
from .videomerger import NODE_DISPLAY_NAME_MAPPINGS as VIDEO_MERGER_NODE_DISPLAY_NAME_MAPPINGS
from .vibe_music_engine import NODE_CLASS_MAPPINGS as VIBE_NODE_CLASS_MAPPINGS
from .vibe_music_engine import NODE_DISPLAY_NAME_MAPPINGS as VIBE_NODE_DISPLAY_NAME_MAPPINGS
from .base_path_node import NODE_CLASS_MAPPINGS as BASE_PATH_NODE_CLASS_MAPPINGS
from .base_path_node import NODE_DISPLAY_NAME_MAPPINGS as BASE_PATH_NODE_DISPLAY_NAME_MAPPINGS
from .simple_image_loader import NODE_CLASS_MAPPINGS as IMAGE_LOADER_NODE_CLASS_MAPPINGS
from .simple_image_loader import NODE_DISPLAY_NAME_MAPPINGS as IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .number_padder import NODE_CLASS_MAPPINGS as NUMBER_PADDER_NODE_CLASS_MAPPINGS
from .number_padder import NODE_DISPLAY_NAME_MAPPINGS as NUMBER_PADDER_NODE_DISPLAY_NAME_MAPPINGS
from .text_file_loader import NODE_CLASS_MAPPINGS as TEXT_LOADER_NODE_CLASS_MAPPINGS
from .text_file_loader import NODE_DISPLAY_NAME_MAPPINGS as TEXT_LOADER_NODE_DISPLAY_NAME_MAPPINGS
from .imgbb_uploader import NODE_CLASS_MAPPINGS as IMGBB_NODE_CLASS_MAPPINGS
from .imgbb_uploader import NODE_DISPLAY_NAME_MAPPINGS as IMGBB_NODE_DISPLAY_NAME_MAPPINGS
from .tuple_counter import NODE_CLASS_MAPPINGS as TUPLE_COUNTER_NODE_CLASS_MAPPINGS
from .tuple_counter import NODE_DISPLAY_NAME_MAPPINGS as TUPLE_COUNTER_NODE_DISPLAY_NAME_MAPPINGS
from .file_path_processor import NODE_CLASS_MAPPINGS as FILE_PROCESSOR_NODE_CLASS_MAPPINGS
from .file_path_processor import NODE_DISPLAY_NAME_MAPPINGS as FILE_PROCESSOR_NODE_DISPLAY_NAME_MAPPINGS
from .moving_titles import NODE_CLASS_MAPPINGS as MOVING_TITLES_NODE_CLASS_MAPPINGS
from .moving_titles import NODE_DISPLAY_NAME_MAPPINGS as MOVING_TITLES_NODE_DISPLAY_NAME_MAPPINGS
from .anthropic_chat import NODE_CLASS_MAPPINGS as ANTHROPIC_CHAT_NODE_CLASS_MAPPINGS
from .anthropic_chat import NODE_DISPLAY_NAME_MAPPINGS as ANTHROPIC_CHAT_NODE_DISPLAY_NAME_MAPPINGS

# Combine the node mappings
NODE_CLASS_MAPPINGS = {
    **WIGGLE_NODE_CLASS_MAPPINGS,
    **OPTICAL_NODE_CLASS_MAPPINGS,
    **EDL_NODE_CLASS_MAPPINGS,
    **VIDEO_MERGER_NODE_CLASS_MAPPINGS,
    **VIBE_NODE_CLASS_MAPPINGS,
    **BASE_PATH_NODE_CLASS_MAPPINGS,
    **IMAGE_LOADER_NODE_CLASS_MAPPINGS,
    **NUMBER_PADDER_NODE_CLASS_MAPPINGS,
    **TEXT_LOADER_NODE_CLASS_MAPPINGS,
    **IMGBB_NODE_CLASS_MAPPINGS,
    **TUPLE_COUNTER_NODE_CLASS_MAPPINGS,
    **FILE_PROCESSOR_NODE_CLASS_MAPPINGS,
    **MOVING_TITLES_NODE_CLASS_MAPPINGS,
    **ANTHROPIC_CHAT_NODE_CLASS_MAPPINGS
}

# Combine the display name mappings
NODE_DISPLAY_NAME_MAPPINGS = {
    **WIGGLE_NODE_DISPLAY_NAME_MAPPINGS,
    **OPTICAL_NODE_DISPLAY_NAME_MAPPINGS,
    **EDL_NODE_DISPLAY_NAME_MAPPINGS,
    **VIDEO_MERGER_NODE_DISPLAY_NAME_MAPPINGS,
    **VIBE_NODE_DISPLAY_NAME_MAPPINGS,
    **BASE_PATH_NODE_DISPLAY_NAME_MAPPINGS,
    **IMAGE_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **NUMBER_PADDER_NODE_DISPLAY_NAME_MAPPINGS,
    **TEXT_LOADER_NODE_DISPLAY_NAME_MAPPINGS,
    **IMGBB_NODE_DISPLAY_NAME_MAPPINGS,
    **TUPLE_COUNTER_NODE_DISPLAY_NAME_MAPPINGS,
    **FILE_PROCESSOR_NODE_DISPLAY_NAME_MAPPINGS,
    **MOVING_TITLES_NODE_DISPLAY_NAME_MAPPINGS,
    **ANTHROPIC_CHAT_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']